WITH UNITS_LEASES AS (
	SELECT *
	FROM {{ ref('int_mixed_units_leases_all') }}
),
LEASES_CHARGES AS (
	SELECT *
	FROM {{ ref('int_mixed_leases_charges_all') }}
),
DETAIL_ROWS AS (
	SELECT
		UNITS_LEASES."PROP_ID" AS "PROP_ID",
		UNITS_LEASES."PROP_NAME" AS "PROP_NAME",
		UNITS_LEASES."UNIT_ID" AS "UNIT_ID",
		UNITS_LEASES."UNIT_NAME" AS "UNIT_NAME",
		UNITS_LEASES."UNIT_SQ_FT" AS "UNIT_SQ_FT",
		UNITS_LEASES."LEASE_ID" AS "LEASE_ID",
		UNITS_LEASES."LEASE_NAME" AS "LEASE_NAME",
		UNITS_LEASES."lease_created_at" AS "lease_created_at",
		UNITS_LEASES."lease_start" AS "lease_start",
		UNITS_LEASES."unit_move_in" AS "unit_move_in",
		UNITS_LEASES."lease_end" AS "lease_end",
		UNITS_LEASES."LEASE_TERMINATION" AS "LEASE_TERMINATION",
		UNITS_LEASES."LEASE_RAW_STATUS" AS "LEASE_RAW_STATUS",
		UNITS_LEASES."LEASE_STATUS" AS "LEASE_STATUS",
		CASE
			WHEN UNITS_LEASES."LEASE_ID" IS NULL THEN 'VACANT'
			ELSE 'OCCUPIED'
		END AS "OCCUPANCY_STATUS",
		UNITS_LEASES."UNIT_STATUS" AS "UNIT_STATUS",
		UNITS_LEASES."DEPOSIT" AS "DEPOSIT",
		UNITS_LEASES."REFUNDABLE" AS "REFUNDABLE",
		UNITS_LEASES."TENANT_NAME" AS "TENANT_NAME",
		UNITS_LEASES."company_relation_id" AS "company_relation_id",
		UNITS_LEASES."month_to_month" AS "month_to_month",
		UNITS_LEASES."month_to_month_label" AS "month_to_month_label",
		COALESCE(LEASES_CHARGES."RENT_AMOUNT", 0) AS "RENT_AMOUNT",
		COALESCE(LEASES_CHARGES."OTHER_AMOUNT", 0) AS "OTHER_AMOUNT",
		COALESCE(LEASES_CHARGES."ANNUAL_RENT_AMOUNT", 0) AS "ANNUAL_RENT_AMOUNT",
		COALESCE(LEASES_CHARGES."ANNUAL_OTHER_AMOUNT", 0) AS "ANNUAL_OTHER_AMOUNT",
		COALESCE(LEASES_CHARGES."RENT_AMOUNT", 0) + COALESCE(LEASES_CHARGES."OTHER_AMOUNT", 0) AS "TOTAL_MONTHLY_AMOUNT",
		COALESCE(LEASES_CHARGES."ANNUAL_RENT_AMOUNT", 0) + COALESCE(LEASES_CHARGES."ANNUAL_OTHER_AMOUNT", 0) AS "TOTAL_ANNUAL_AMOUNT",
		GREATEST(
			UNITS_LEASES."_valid_from",
			COALESCE(LEASES_CHARGES."_valid_from", UNITS_LEASES."_valid_from")
		) AS "_valid_from",
		LEAST(
			UNITS_LEASES."_valid_to",
			COALESCE(LEASES_CHARGES."_valid_to", UNITS_LEASES."_valid_to")
		) AS "_valid_to"
	FROM UNITS_LEASES
	LEFT OUTER JOIN LEASES_CHARGES
		ON UNITS_LEASES."LEASE_ID" = LEASES_CHARGES."LEASE_ID"
		AND UNITS_LEASES."UNIT_ID" = LEASES_CHARGES."UNIT_ID"
		AND UNITS_LEASES."_valid_from" < LEASES_CHARGES."_valid_to"
		AND UNITS_LEASES."_valid_to" > LEASES_CHARGES."_valid_from"
),
DETAIL_FILTERED AS (
	SELECT *
	FROM DETAIL_ROWS
	WHERE "_valid_from" < "_valid_to"
),
LEASES_PER_UNIT_PERIOD AS (
	SELECT
		DETAIL_FILTERED."UNIT_ID",
		DETAIL_FILTERED."_valid_from",
		DETAIL_FILTERED."_valid_to",
		COUNT(DISTINCT UNITS_LEASES."LEASE_ID") FILTER (WHERE UNITS_LEASES."LEASE_ID" IS NOT NULL) AS "LEASES_COUNT"
	FROM DETAIL_FILTERED
	LEFT OUTER JOIN UNITS_LEASES
		ON DETAIL_FILTERED."UNIT_ID" = UNITS_LEASES."UNIT_ID"
		AND DETAIL_FILTERED."_valid_from" < UNITS_LEASES."_valid_to"
		AND DETAIL_FILTERED."_valid_to" > UNITS_LEASES."_valid_from"
	GROUP BY
		DETAIL_FILTERED."UNIT_ID",
		DETAIL_FILTERED."_valid_from",
		DETAIL_FILTERED."_valid_to"
)

select
	DETAIL_FILTERED."PROP_ID" AS "PROP_ID",
	DETAIL_FILTERED."PROP_NAME" AS "PROP_NAME",
	DETAIL_FILTERED."UNIT_ID" AS "UNIT_ID",
	DETAIL_FILTERED."UNIT_NAME" AS "UNIT_NAME",
	DETAIL_FILTERED."UNIT_SQ_FT" AS "UNIT_SQ_FT",
	CASE
		WHEN COALESCE(LEASES_PER_UNIT_PERIOD."LEASES_COUNT", 0) = 0 THEN DETAIL_FILTERED."UNIT_SQ_FT"
		ELSE DETAIL_FILTERED."UNIT_SQ_FT" / LEASES_PER_UNIT_PERIOD."LEASES_COUNT"
	END AS "UNIT_SQ_FT_ALLOCATED",
	DETAIL_FILTERED."LEASE_ID" AS "LEASE_ID",
	DETAIL_FILTERED."LEASE_NAME" AS "LEASE_NAME",
	DETAIL_FILTERED."lease_created_at" AS "lease_created_at",
	DETAIL_FILTERED."lease_start" AS "lease_start",
	DETAIL_FILTERED."unit_move_in" AS "unit_move_in",
	DETAIL_FILTERED."lease_end" AS "lease_end",
	DETAIL_FILTERED."LEASE_TERMINATION" AS "LEASE_TERMINATION",
	DETAIL_FILTERED."LEASE_RAW_STATUS" AS "LEASE_RAW_STATUS",
	DETAIL_FILTERED."LEASE_STATUS" AS "LEASE_STATUS",
	DETAIL_FILTERED."OCCUPANCY_STATUS" AS "OCCUPANCY_STATUS",
	DETAIL_FILTERED."UNIT_STATUS" AS "UNIT_STATUS",
	DETAIL_FILTERED."DEPOSIT" AS "DEPOSIT",
	DETAIL_FILTERED."REFUNDABLE" AS "REFUNDABLE",
	DETAIL_FILTERED."TENANT_NAME" AS "TENANT_NAME",
	DETAIL_FILTERED."company_relation_id" AS "company_relation_id",
	DETAIL_FILTERED."month_to_month" AS "month_to_month",
	DETAIL_FILTERED."month_to_month_label" AS "month_to_month_label",
	DETAIL_FILTERED."RENT_AMOUNT" AS "RENT_AMOUNT",
	DETAIL_FILTERED."OTHER_AMOUNT" AS "OTHER_AMOUNT",
	DETAIL_FILTERED."TOTAL_MONTHLY_AMOUNT" AS "TOTAL_MONTHLY_AMOUNT",
	DETAIL_FILTERED."ANNUAL_RENT_AMOUNT" AS "ANNUAL_RENT_AMOUNT",
	DETAIL_FILTERED."ANNUAL_OTHER_AMOUNT" AS "ANNUAL_OTHER_AMOUNT",
	DETAIL_FILTERED."TOTAL_ANNUAL_AMOUNT" AS "TOTAL_ANNUAL_AMOUNT",
	LEASES_PER_UNIT_PERIOD."LEASES_COUNT" AS "LEASES_COUNT",
	CASE
		WHEN COALESCE(DETAIL_FILTERED."UNIT_SQ_FT", 0) = 0 THEN 0
		ELSE DETAIL_FILTERED."TOTAL_ANNUAL_AMOUNT" / DETAIL_FILTERED."UNIT_SQ_FT"
	END AS "ANNUAL_AMOUNT_PER_SQ_FT",
	DETAIL_FILTERED."_valid_from" AS "_valid_from",
	DETAIL_FILTERED."_valid_to" AS "_valid_to"
from DETAIL_FILTERED
left outer join LEASES_PER_UNIT_PERIOD
	on DETAIL_FILTERED."UNIT_ID" = LEASES_PER_UNIT_PERIOD."UNIT_ID"
	and DETAIL_FILTERED."_valid_from" = LEASES_PER_UNIT_PERIOD."_valid_from"
	and DETAIL_FILTERED."_valid_to" = LEASES_PER_UNIT_PERIOD."_valid_to"
