WITH SQ_FT_TEMP AS (
	SELECT
		UNITS."PROP_ID" as "PROP_ID",
		SUM(UNITS."UNIT_SQ_FT") AS "TOT_SQ_FT"
	 
	FROM  {{ ref('units') }} as UNITS

	GROUP BY  UNITS."PROP_ID"
	),
FINAL AS (
	select 
		"LEASE_ID",
		"UNIT_ID",
		"lease_created_at", 
		"start",
		"lease_end",
		"TENANT",
		"LEASE_STATUS",
		"DEPOSIT",
		"REFUNDABLE",
		"RENT_AMOUNT",
		"OTHER_AMOUNT",
		"ANNUAL_RENT_AMOUNT",
		"ANNUAL_OTHER_AMOUNT"
	from {{ ref('leases_charges') }} as LEASES_CHARGES
	group by 
		"LEASE_ID",
		"UNIT_ID",
		"lease_created_at", 
		"start",
		"lease_end",
		"TENANT",
		"LEASE_STATUS",
		"DEPOSIT",
		"REFUNDABLE",
		"RENT_AMOUNT",
		"OTHER_AMOUNT",
		"ANNUAL_RENT_AMOUNT",
		"ANNUAL_OTHER_AMOUNT"
	ORDER BY LEASES_CHARGES."LEASE_ID"
	),
FINAL_AUX AS (
    SELECT COUNT(DISTINCT "LEASE_ID") "LEASES_COUNT",
    "UNIT_ID"
    FROM FINAL
    GROUP BY "UNIT_ID"
	)

SELECT 
UNITS."PROP_ID",
UNITS."PROP_NAME",
UNITS."UNIT_ID",
UNITS."UNIT_NAME" "UNIT_NAME" ,
FINAL."LEASE_ID",
CASE WHEN FINAL."lease_created_at" IS NOT NULL THEN 'OCCUPIED' ELSE 'VACANT' END AS  "LEASE_STATUS", 
FINAL."TENANT",
FINAL."lease_created_at" "lease_created_at",
FINAL."start" "lease_start",
FINAL."lease_end",	
UNITS."UNIT_SQ_FT" "UNIT_SQ_FT",
CASE 	WHEN (FINAL_AUX."LEASES_COUNT" = 0 OR FINAL_AUX."LEASES_COUNT" IS NULL) THEN UNITS."UNIT_SQ_FT" 
		ELSE UNITS."UNIT_SQ_FT"/FINAL_AUX."LEASES_COUNT" 
	END AS "UNIT_SQ_FT_fix",
CASE 	WHEN SQ_FT_TEMP."TOT_SQ_FT" = 0 THEN 0 
		ELSE UNITS."UNIT_SQ_FT" / SQ_FT_TEMP."TOT_SQ_FT" * 100 
	END AS "Pct of Property",
CASE 	WHEN SQ_FT_TEMP."TOT_SQ_FT" = 0 THEN 0 
		ELSE ("UNIT_SQ_FT"/FINAL_AUX."LEASES_COUNT") / SQ_FT_TEMP."TOT_SQ_FT" * 100 
	END AS "Pct of Property_fix",
FINAL."DEPOSIT",
FINAL."REFUNDABLE",
FINAL."RENT_AMOUNT" "RENT_AMOUNT",
FINAL."OTHER_AMOUNT" "OTHER_AMOUNT",
FINAL."ANNUAL_RENT_AMOUNT" "ANNUAL_RENT_AMOUNT",
FINAL."ANNUAL_OTHER_AMOUNT" "ANNUAL_OTHER_AMOUNT",
CASE WHEN UNITS."UNIT_SQ_FT" = 0 THEN 0 ELSE FINAL."RENT_AMOUNT" *12 /UNITS."UNIT_SQ_FT" END AS "Annual Rent/Sq Ft",
CASE WHEN UNITS."UNIT_SQ_FT" = 0 THEN 0 ELSE FINAL."OTHER_AMOUNT" *12 /UNITS."UNIT_SQ_FT" END AS "Annual Other/Sq Ft"

FROM {{ ref('units') }} as UNITS
LEFT JOIN SQ_FT_TEMP
	ON UNITS."PROP_ID" = SQ_FT_TEMP."PROP_ID"
LEFT JOIN FINAL
	ON UNITS."UNIT_ID" = FINAL."UNIT_ID"
LEFT JOIN FINAL_AUX
	ON FINAL."UNIT_ID" = FINAL_AUX."UNIT_ID"
INNER JOIN "public"."properties"
		ON UNITS."PROP_ID" = "public"."properties"."id"
		
where  "PROP_NAME" IN (@Property_Name)
	AND CAST("public"."properties"."company_relation_id" AS INT)  = CAST(@REAL_COMPANY_ID AS INT)

order by "PROP_NAME", UNITS."UNIT_NAME"